
retriever:
  file: "retriever/google-2024-environmental-report.pdf"
  headers_to_split_on:
    - ["#", "Header 1"]
    - ["##", "Header 2"]
  load_documents: True
  collection_name: rag-chroma-google
  directory: vector_db
  top_k: 3
  top_k_compression: 3
  ensemble_weights: [0.3, 0.3, 0.4] 
  cohere_rerank_model: rerank-english-v3.0
llm:
  gpt_4o_mini: gpt-4o-mini-2024-07-18
  gpt_4o: gpt-4o-2024-08-06
  temperature: 0

description: |
  what is config.yaml file for MultiAgenticRAG
  It's simply a configuration file. Instead of hardcoding values in your Python code, you keep them in one place.

  difference
  .env → Secrets (API keys, passwords, tokens).
  config.yaml → Normal settings (model name, chunk size, file paths, temperature).
